# kaomoji

name: kaomoji
parent: default

matches:
  - trigger: "::fliptable"
    replace: "(╯°□°）╯︵ ┻━┻"
  - trigger: "::shrug"
    replace: "¯\_(ツ)_/¯"
  - trigger: "::heyhey"
    replace: "( ͡° ͜ ͡°)"
  - trigger: "::disapprove"
    replace: "ಠ_ಠ"
  - trigger: "::hello"
    replace: "( ･_･)ﾉ"
  - trigger: "::cry"
    replace: "ಥ益ಥ"
  - trigger: "::mad"
    replace: "(๑•̀д•́๑)"
  - trigger: "::awk"
    replace: "( ་___ ་ )"
  - trigger: "::pika"
    replace: "(๑◕ܫ◕๑)"
  - trigger: "::poodoo"
    replace: "ヽ༼ຈل͜ຈ༽ﾉ"
  - trigger: "::sparkle"
    replace: "✧･ﾟ: *✧･ﾟ:* 　$|$　 *:･ﾟ✧*:･ﾟ✧"

